#!/usr/bin/env node
/**
 * Reads all .pem files from countries/<cc>/current/ and generates
 * countries/<cc>/index.js with named exports of PEM strings.
 *
 * Usage: node scripts/generate-exports.mjs
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(fileURLToPath(import.meta.url), '..', '..')

function toExportName(filename) {
  return filename
    .replace(/\.pem$/i, '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
    .toUpperCase()
}

const countriesDir = join(root, 'countries')
const countries = readdirSync(countriesDir).filter((d) =>
  statSync(join(countriesDir, d)).isDirectory(),
)

const reExports = []

for (const cc of countries) {
  const currentDir = join(countriesDir, cc, 'current')
  let pemFiles
  try {
    pemFiles = readdirSync(currentDir).filter(
      (f) => f.endsWith('.pem') && f !== 'chain.pem',
    )
  } catch {
    continue
  }

  pemFiles.sort()

  const lines = [
    '// Auto-generated by scripts/generate-exports.mjs — do not edit manually.',
    '// Source: countries/' + cc + '/current/*.pem',
    '',
  ]

  const certEntries = []

  for (const file of pemFiles) {
    const pem = readFileSync(join(currentDir, file), 'utf-8').trim()
    const name = toExportName(file)
    const label = basename(file, '.pem')

    lines.push(`export const ${name} = \`${pem}\``)
    lines.push('')

    certEntries.push(`  { name: '${label}', exportName: '${name}', pem: ${name} }`)
  }

  lines.push('/** All certificates for this country, in alphabetical order. */')
  lines.push('export const ALL_CERTS = [')
  lines.push(certEntries.join(',\n'))
  lines.push(']')
  lines.push('')

  const outPath = join(countriesDir, cc, 'index.js')
  writeFileSync(outPath, lines.join('\n'))
  console.log(`  wrote ${outPath} (${pemFiles.length} certs)`)

  reExports.push(`export * as ${cc} from './countries/${cc}/index.js'`)
}

// Root index.js
const rootIndex = [
  '// Auto-generated by scripts/generate-exports.mjs — do not edit manually.',
  '',
  ...reExports,
  '',
].join('\n')

writeFileSync(join(root, 'index.js'), rootIndex)
console.log(`  wrote index.js (${countries.length} country/ies)`)
