#!/usr/bin/env node
/**
 * Reads all .pem files from countries/<cc>/current/ and generates
 * countries/<cc>/index.js with named exports of PEM strings.
 *
 * Usage: node scripts/generate-exports.mjs
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(fileURLToPath(import.meta.url), '..', '..')

function toExportName(filename) {
  return filename
    .replace(/\.pem$/i, '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
    .toUpperCase()
}

/**
 * Pure renderer: given a country code and cert list, returns the index.js content.
 * certs: Array<{ file: string, pem: string, sha256: string }>
 *
 * <= 20 certs: per-cert named consts + ALL_CERTS (current behaviour)
 * > 20 certs: ALL_CERTS (with sha256) + getBySha256 only, no per-cert consts
 */
export function renderCountryIndex(cc, certs) {
  const lines = [
    '// Auto-generated by scripts/generate-exports.mjs — do not edit manually.',
    '// Source: countries/' + cc + '/current/*.pem',
    '',
  ]

  if (certs.length <= 20) {
    const certEntries = []
    for (const { file, pem } of certs) {
      const name = toExportName(file)
      const label = basename(file, '.pem')
      lines.push(`export const ${name} = \`${pem}\``)
      lines.push('')
      certEntries.push(`  { name: '${label}', exportName: '${name}', pem: ${name} }`)
    }
    lines.push('/** All certificates for this country, in alphabetical order. */')
    lines.push('export const ALL_CERTS = [')
    lines.push(certEntries.join(',\n'))
    lines.push(']')
    lines.push('')
  } else {
    const certEntries = []
    for (const { file, pem, sha256 } of certs) {
      const name = toExportName(file)
      const label = basename(file, '.pem')
      certEntries.push(
        `  { name: '${label}', exportName: '${name}', pem: \`${pem}\`, sha256: '${sha256}' }`,
      )
    }
    lines.push('/** All certificates for this country, in alphabetical order. */')
    lines.push('export const ALL_CERTS = [')
    lines.push(certEntries.join(',\n'))
    lines.push(']')
    lines.push('')
    lines.push('/** Look up a certificate by its SHA-256 fingerprint (hex). */')
    lines.push('export function getBySha256(hex) {')
    lines.push("  return ALL_CERTS.find((c) => c.sha256 === hex) ?? null")
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// Only run the generator when invoked directly (not when imported by tests)
const isMain =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]

if (isMain) {
  const countriesDir = join(root, 'countries')
  const countries = readdirSync(countriesDir).filter((d) =>
    statSync(join(countriesDir, d)).isDirectory(),
  )

  const reExports = []

  for (const cc of countries) {
    const currentDir = join(countriesDir, cc, 'current')
    let manifestEntries
    try {
      const manifestPath = join(currentDir, 'manifest.json')
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'))
      manifestEntries = manifest.certificates
    } catch {
      continue
    }

    // Sort by file name (same order as before)
    manifestEntries = [...manifestEntries].sort((a, b) => a.file.localeCompare(b.file))

    const certs = manifestEntries.map((entry) => {
      const pem = readFileSync(join(currentDir, entry.file), 'utf-8').trim()
      return { file: entry.file, pem, sha256: entry.sha256 }
    })

    const content = renderCountryIndex(cc, certs)
    const outPath = join(countriesDir, cc, 'index.js')
    writeFileSync(outPath, content)
    console.log(`  wrote ${outPath} (${certs.length} certs)`)

    // The root barrel aliases each country under a JS-identifier-safe name.
    // Most codes are already valid (two-letter ISO), but special pseudo-codes
    // like "cl-estado" contain a hyphen, which is illegal in an ESM binding
    // name (`export * as cl-estado` is a syntax error). Underscore them for the
    // barrel; consumers reach these via the subpath export (@attestto/trust/cl-estado)
    // or by importing countries/<cc>/index.js directly.
    const alias = cc.replace(/[^A-Za-z0-9$_]/g, '_')
    reExports.push(`export * as ${alias} from './countries/${cc}/index.js'`)
  }

  // Root index.js
  const rootIndex = [
    '// Auto-generated by scripts/generate-exports.mjs — do not edit manually.',
    '',
    ...reExports,
    '',
  ].join('\n')

  writeFileSync(join(root, 'index.js'), rootIndex)
  console.log(`  wrote index.js (${countries.length} country/ies)`)
}
